AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.9

  Sample SAM Template for similarity-engine-word2vec-model

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900
    Tracing: Active
  Api:
    TracingEnabled: True
    

Resources:
  SimilarityEngineWord2VecFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: similarity-engine-word2vec-model-dev/ #required if PackageType is Zip. Path to app.py and requirement.txt
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
      - x86_64
      MemorySize: 1024
      Events:
        SimilarityEngineWord2Vec:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /similarity-engine-word2vec-model-dev
            Method: get
      Layers:
      - arn:aws:lambda:ca-central-1:336392948345:layer:AWSSDKPandas-Python39:10 # AWS SDK for pandas https://aws-sdk-pandas.readthedocs.io/en/stable/layers.html
      
      

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SimilarityEngineWord2VecFunctionApi:
    Description: "API Gateway endpoint URL for Prod stage for Similarity Engine Data Process function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  SimilarityEngineWord2VecFunction:
    Description: "Similarity Engine Data Process Lambda Function ARN"
    Value: !GetAtt SimilarityEngineWord2VecFunction.Arn