AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.9

  Sample SAM Template for similarity-engine-data-process-dev

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900
    Tracing: Active
  Api:
    TracingEnabled: True

Resources:
  SimilarityEngineDataProcessFunctionV2:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: similarity-engine-data-process/ #required if PackageType is Zip. Path to app.py and requirement.txt
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      MemorySize: 1024
      Timeout: 900
      Events:
        SimilarityEngineDataProcess:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /similarity_engine-data-process
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SimilarityEngineDataProcessFunctionApi:
    Description: "API Gateway endpoint URL for Prod stage for Similarity Engine Data Process function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  SimilarityEngineDataProcessFunctionV2:
    Description: "Similarity Engine Data Process Lambda Function ARN"
    Value: !GetAtt SimilarityEngineDataProcessFunctionV2.Arn

